---
clone: 
  depth: 1
kind: pipeline
type: docker
name: linux-amd64

steps:
- name: Compile
  image: ubuntu:18.04
  commands:
      - apt-get -y update && apt-get -y upgrade && apt-get -y install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev repo rsync flex bison cpio
      - git config --global user.name "neonmicky"
      - git config --global user.email "neonmicky30@gmail.com"
      - git config --global color.ui false
      - mkdir nm && cd nm
      - wget https://raw.githubusercontent.com/labneon/kernel_xiaomi_tissot/eleven/build.sh
      - bash build.sh
